# Generated by Django 5.2 on 2025-07-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_eventlog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
